---
- name: Restart docker
  service:
    name: 'docker'
    state: 'restarted'

- name: Restart main buildkite agent
  become: yes
  become_user: root
  systemd:
    name: buildkite-agent
    state: restarted

- name: Restart clone buildkite agents
  become: yes
  become_user: root
  systemd:
    name: buildkite-agent@{{item}}
    state: restarted
  with_sequence: start=1 end={{buildkite_agent_count}}
